### ISSUE TITLE
Disabled and Readonly seem not to work

### ISSUE THREAD

**Issue by shadikhani** [vaadin/vaadin-list-box#58] opened 2019-10-23 09:28 UTC
When tried to use disable or readonly attributes like `disabled="" has-label="" aria-disabled="true"` or `disabled` for the vaadin-list-box , they did not work.

**Comment by web-padawan** [comment] 2019-10-23 09:51
Duplicate of #9

**Closed by web-padawan** 2019-10-23 09:51 UTC
