### ISSUE TITLE
Should we introduce value property?

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-list-box#8] opened 2017-11-10 08:10 UTC
One of the UX/DX tests participant propose to introduce `value` property to `vaadin-list-box` to align with `vaadin-dropdown-menu` where it is currently used.

**Comment by web-padawan** [comment] 2019-06-03 07:55
Closing as duplicate of https://github.com/vaadin/vaadin-list-mixin/issues/24.

Let's keep that one open and decide whether we want this to land after V15.

**Closed by web-padawan** 2019-06-03 07:56 UTC
Labels: UX/DX finding
